import Link from 'next/link';
import ThemeToggle from '@/components/ThemeToggle';
import {
  Sparkles,
  ArrowRight,
  Wrench,
  MessageSquare,
  Workflow,
  UserPlus,
  Zap,
  BookOpen,
  Layers,
  BarChart3,
  Scale,
} from 'lucide-react';

interface DemoCard {
  title: string;
  description: string;
  href: string;
  icon: React.ElementType;
  gradient: string;
  tags: string[];
  isNew?: boolean;
}

const demos: DemoCard[] = [
  {
    title: 'Sparkle Enhancement',
    description: 'Simple textarea with AI enhancement button. Uses Vercel AI SDK streaming.',
    href: '/sparkle-demo',
    icon: Sparkles,
    gradient: 'from-purple-500 to-pink-500',
    tags: ['Vercel AI SDK', 'Streaming', 'Basic'],
  },
  {
    title: 'Multi-Step Wizard',
    description: 'Profile wizard with AI sparkle enhancement on every field. 4-step form flow.',
    href: '/profile',
    icon: Wrench,
    gradient: 'from-blue-500 to-cyan-500',
    tags: ['Vercel AI SDK', 'Multi-step', 'Forms'],
  },
  {
    title: 'CopilotKit Basic',
    description: 'Simple demo of useCopilotReadable and useCopilotAction with Generative UI.',
    href: '/copilot-test',
    icon: MessageSquare,
    gradient: 'from-green-500 to-emerald-500',
    tags: ['CopilotKit', 'Generative UI', 'Basic'],
  },
  {
    title: 'AI-Powered Wizard',
    description: 'Full wizard with chat-driven auto-fill, field enhancement, and navigation.',
    href: '/ai-wizard',
    icon: Workflow,
    gradient: 'from-orange-500 to-red-500',
    tags: ['CopilotKit', 'Generative UI', 'Forms'],
    isNew: true,
  },
  {
    title: 'Interactive Onboarding',
    description: 'Conversational onboarding with clickable Generative UI cards. Split-screen layout.',
    href: '/ai-onboarding',
    icon: UserPlus,
    gradient: 'from-violet-500 to-purple-500',
    tags: ['CopilotKit', 'Generative UI', 'Onboarding'],
    isNew: true,
  },
  {
    title: 'Hybrid Sparkle + Chat',
    description: 'Best of both worlds: Quick sparkle buttons for single fields + chat for bulk operations.',
    href: '/hybrid-demo',
    icon: Layers,
    gradient: 'from-amber-500 to-orange-500',
    tags: ['Vercel AI SDK', 'CopilotKit', 'Hybrid'],
    isNew: true,
  },
  {
    title: 'AI Dashboard Assistant',
    description: 'SaaS metrics dashboard with AI insights, conversational data exploration, and drill-down explanations.',
    href: '/ai-dashboard',
    icon: BarChart3,
    gradient: 'from-cyan-500 to-blue-500',
    tags: ['CopilotKit', 'Data Viz', 'Recharts'],
    isNew: true,
  },
  {
    title: 'AI Compare & Decide',
    description: 'Comparison tables, pros/cons lists, recommendations, and decision matrices generated by AI.',
    href: '/ai-compare',
    icon: Scale,
    gradient: 'from-indigo-500 to-purple-500',
    tags: ['CopilotKit', 'Generative UI', 'Decisions'],
    isNew: true,
  },
];

export default function Home() {
  return (
    <main className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 transition-colors">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-12">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 bg-gradient-to-br from-purple-500 to-blue-500 rounded-xl">
                <Zap className="w-6 h-6 text-white" />
              </div>
              <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
                AI Prototypes
              </h1>
            </div>
            <p className="text-gray-600 dark:text-gray-400">
              Exploring AI-enhanced UI patterns with Vercel AI SDK and CopilotKit
            </p>
          </div>
          <ThemeToggle />
        </div>

        {/* Demo Cards Grid */}
        <div className="grid md:grid-cols-2 gap-6 mb-12">
          {demos.map((demo) => {
            const Icon = demo.icon;
            return (
              <Link
                key={demo.href}
                href={demo.href}
                className="group relative bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 overflow-hidden hover:shadow-lg hover:border-gray-300 dark:hover:border-gray-600 transition-all"
              >
                {/* Gradient Header */}
                <div className={`h-2 bg-gradient-to-r ${demo.gradient}`} />

                <div className="p-6">
                  {/* Icon & Title Row */}
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-3">
                      <div
                        className={`p-2.5 rounded-xl bg-gradient-to-br ${demo.gradient} text-white`}
                      >
                        <Icon className="w-5 h-5" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                            {demo.title}
                          </h2>
                          {demo.isNew && (
                            <span className="px-2 py-0.5 text-xs font-medium bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 rounded-full">
                              New
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                    <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-gray-600 dark:group-hover:text-gray-300 group-hover:translate-x-1 transition-all" />
                  </div>

                  {/* Description */}
                  <p className="text-gray-600 dark:text-gray-400 text-sm mb-4">
                    {demo.description}
                  </p>

                  {/* Tags */}
                  <div className="flex flex-wrap gap-2">
                    {demo.tags.map((tag) => (
                      <span
                        key={tag}
                        className="px-2.5 py-1 text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 rounded-full"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
              </Link>
            );
          })}
        </div>

        {/* Info Section */}
        <div className="grid md:grid-cols-2 gap-6">
          {/* Tech Stack */}
          <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
            <div className="flex items-center gap-2 mb-4">
              <Zap className="w-5 h-5 text-yellow-500" />
              <h3 className="font-semibold text-gray-900 dark:text-white">Tech Stack</h3>
            </div>
            <ul className="space-y-2 text-sm text-gray-600 dark:text-gray-400">
              <li className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-blue-500" />
                Next.js 15 (App Router)
              </li>
              <li className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-purple-500" />
                Vercel AI SDK (useCompletion, streamText)
              </li>
              <li className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-green-500" />
                CopilotKit (Generative UI, Actions)
              </li>
              <li className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-cyan-500" />
                Tailwind CSS v4 + Dark Mode
              </li>
              <li className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-orange-500" />
                OpenAI GPT-4o-mini
              </li>
            </ul>
          </div>

          {/* Documentation */}
          <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
            <div className="flex items-center gap-2 mb-4">
              <BookOpen className="w-5 h-5 text-blue-500" />
              <h3 className="font-semibold text-gray-900 dark:text-white">Documentation</h3>
            </div>
            <ul className="space-y-2 text-sm">
              <li>
                <code className="text-purple-600 dark:text-purple-400">ai_docs/ARCHITECTURE.md</code>
                <span className="text-gray-500 dark:text-gray-400"> - Sparkle pattern</span>
              </li>
              <li>
                <code className="text-green-600 dark:text-green-400">ai_docs/copilotkit/</code>
                <span className="text-gray-500 dark:text-gray-400"> - CopilotKit guides</span>
              </li>
              <li className="pt-2 text-gray-500 dark:text-gray-400">
                See <code className="text-gray-700 dark:text-gray-300">07-EXPERIMENT-IDEAS.md</code> for future prototypes
              </li>
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 text-center text-sm text-gray-500 dark:text-gray-400">
          Built for exploring AI-enhanced UI patterns • January 2026
        </div>
      </div>
    </main>
  );
}
